# Generated by Django 2.2.19 on 2023-01-07 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='favorite',
            name='recipes.models_unique_user_recipe_link',
        ),
        migrations.RemoveConstraint(
            model_name='shoppingcart',
            name='recipes.models_unique_user_recipe_link',
        ),
        migrations.AddConstraint(
            model_name='favorite',
            constraint=models.UniqueConstraint(fields=('user', 'recipe'), name='recipes.models_unique_user_recipe'),
        ),
        migrations.AddConstraint(
            model_name='shoppingcart',
            constraint=models.UniqueConstraint(fields=('user', 'recipe'), name='recipes.models_unique_user_recipe'),
        ),
    ]
