# Generated by Django 2.2.19 on 2022-12-17 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20221216_1452'),
        ('recipes', '0002_auto_20221216_1453'),
    ]

    operations = [
    ]
