# Generated by Django 2.2.19 on 2022-12-21 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20221221_1930'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='tagrecipe',
            constraint=models.UniqueConstraint(fields=('recipe', 'tag'), name='one_add_per_ingredient'),
        ),
    ]
