# Generated by Django 2.2.19 on 2022-12-08 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20221207_2106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredienttorecipe',
            name='ingredient',
        ),
        migrations.AddField(
            model_name='ingredienttorecipe',
            name='ingredient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipe', to='recipes.Ingredient', verbose_name='Ингредиент'),
        ),
    ]
