# Generated by Django 2.2.19 on 2022-12-24 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_auto_20221221_1954'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ingredienttorecipe',
            name='one_add_per_ingredient',
        ),
    ]
