# Generated by Django 2.2.19 on 2022-12-24 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_auto_20221224_1319'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='ingredienttorecipe',
            constraint=models.UniqueConstraint(fields=('recipe', 'ingredient'), name='one_add_per_ingredient'),
        ),
    ]
