# Generated by Django 2.2.19 on 2022-12-08 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_auto_20221208_2044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredienttorecipe',
            name='measurement_unit',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='measurement_unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='recipes.Measure', verbose_name='Единица измерения'),
        ),
    ]
