# Generated by Django 2.2.19 on 2022-12-08 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_auto_20221208_2317'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='favorite',
            name='one_add_per_recipe',
        ),
    ]
